var x=function(){var a={Z:{},db:{},n:{},c:{},P:{},e:{},G:{},index:{},C:{},p:{},h:{},transaction:{},B:window.IDBTransaction,window:window,cursor:{direction:{}},s:function(b){var d={};if(a.u(b))return parseInt(b,10);if(a.isArray(b))return b.slice(0);a.i(b,function(b,e){d[b]=a.A(e)?a.s(e):e});return d},l:function(b){return x.q(b,void 0)&&x.q(b,null)&&x.q(b,"")&&(!a.isArray(b)||0<b.length)?!1:!0},b:function(b){return a.l(b)?!1:!0},contains:function(b,d,c){var e=!1;a.b(b)&&a.i(b,function(b,g){if(a.j(c,
!0)&&a.j(b,d)||a.j(g,d))e=!0});return e},m:function(b,d){for(var c=d.split("."),e=c.shift();e;){if(a.l(b[e]))return!1;b=b[e];e=c.shift()}return!0},j:function(a,d){return d===a},q:function(){return!1===a.j.apply(a,argument)},A:function(b){return a.v("object",b)&&"[object Object]"===b.toString()},Q:function(b){return a.v("string",b)},k:function(b){return a.v("function",b)},isArray:function(a){return a instanceof Array},H:function(b){b=parseInt(b,10);return a.j(!1,a.u(b))?null:b},u:function(b){return a.v("number",
b)||!1===isNaN(parseInt(b,10))},aa:function(a){return null===a},ba:function(a){return void 0===a},K:function(b){return a.v("boolean",b)||"true"===b||"false"===b},v:function(a,d){return a===typeof d},extend:function(b,d,c){a.i(a.s(d),function(d,f){b[d]=a.j(!0,c)&&a.A(f)?a.extend({},f,c):f});return b},i:function(a,d){for(var c in a)a.hasOwnProperty(c)&&d(c,a)},F:function(b,d,c){var e=0,f=b.length,g=1;!0===c&&(g=-g);for(e=0;e<f;e+=g)a.a(d,b[e])},ea:function(b,d){var c=0;a.isArray(b)?a.F(b,function(){c+=
1}):a.A(b)?a.i(b,function(){c+=1}):c=1;a.a(d,[c]);return c},U:function(b,d,c){var e=[];a.isArray(b)?a.F(b,function(b,c){e.push(a.a(c,d))}):a.A(b)?a.i(b,function(b,c){e.push(a.a(c,d))}):e=[];a.a(c,[e]);return e},a:function(b,d,c,e){return a.k(b)?b.apply(c||a,d||[]):a.a(e,[])},fa:function(){return a.b(a.window.indexedDB)},O:function(b,d,c,e,f,g){function h(){k+=1;a.j(k,l)&&a.a(d,arguments)}var l=b.length||0,k=0;a.U(b,{d:function(){a.a(c,arguments);h()},f:function(){a.a(e,arguments);h()},g:function(){a.a(f,
arguments);h()},o:function(){a.a(g,arguments);h()}})}};a.c.close=function(b){var d={c:b},c=a.n[b];a.b(c)&&(a.a(c.close,[d]),delete a.n[b])};a.c.set=function(b,d){return a.n[b]=d};a.c.V=function(b){function d(d){a.b(c)&&(b.D=e.objectStore(c));b.event=d;return b}var c=b.e,e=b.db||a.n[b.c],f=a.H(e.version)||1;a.l(e)||f>e.version?(f=e.setVersion(f),a.extend(f,{onsuccess:function(c){a.a(b.d,[d(c)])},onerror:function(c){a.a(b.f,[d(c)])},onabort:function(c){a.a(b.g,[d(c)])},onblocked:function(c){a.a(b.o,
[d(c)])}})):a.a(b.d,[d(null)])};a.c.I=function(b){function d(d){c=d.db;if(a.b(c.version)&&c.version>=f){var h;a.b(e)&&(b.D=c.objectStore(e));h=[d];a.a(d.d,h);a.q(b.d,d.d)&&a.a(b.d,h)}else a.k(c.setVersion)?a.c.V(d):a.c.W(d)}var c=a.n[b.c],e=b.e,f=a.H(b.version)||c.version+1;a.l(c)?a.c.open({d:function(a){d(a)},f:function(){a.a(b.f,arguments)},g:function(){a.a(b.g,arguments)},o:function(){a.a(b.o,arguments)}}):(b.db=c,d(b))};a.c.W=function(b){function d(d){a.b(c)&&(b.D=f.objectStore(c));b.event=d;
return b}var c=b.e,e=b.c,f=b.db||a.n[e],g=f.version+1||a.H(b.version);a.b(f)&&f.version>=g?(b.db=f,a.a(b.d,[d(null)])):a.extend(a.window.indexedDB.open(e,g),{onsuccess:function(c){a.a(b.d,[d(c)])},onerror:function(c){a.a(b.f,[d(c)])},onabort:function(c){a.a(b.g,[d(c)])},onblocked:function(c){a.a(b.o,[d(c)])},onupgradeneeded:function(c){c=[d(c)];a.q(!1,a.a(b.w,c))&&a.a(b.d,c)}})};a.c.open=function(b){function d(a){b.event=a;return b}var c=b.name,e=b.d,f=b.f,g=b.g,h=b.o;a.extend(a.window.indexedDB.open(c,
b.version),{onsuccess:function(f){b.db=a.c.set(c,f.result||f.target.result);a.a(e,[d(f)])},onblocked:function(b){a.a(h,[d(b)])},onerror:function(b){a.a(f,[d(b)])},onabort:function(b){a.a(g,[d(b)])},onupgradeneeded:function(e){b.db=a.c.set(c,e.target.result||e.result);e=[d(e)];a.q(!1,a.a(b.w,e))&&a.a(b.d,e)}})};a.c.show=function(b){var d=b.c;a.b(a.n[d])?(b.db=a.n[d],a.a(b.r,[b])):a.c.open(b)};a.P.close=function(){a.i(a.n,function(b,d){a.a(d.close,[]);delete a.n[b]})};a.e.clear=function(b,d,c,e,f,g){function h(a){l.event=
a;return l}var l={c:b,e:d,r:g,d:c,f:e,g:f};b=a.transaction.create(b,d,a.transaction.t()).objectStore(d).clear;a.extend(b,{onsuccess:function(b){a.a(l.d,[h(b)])},onerror:function(b){a.a(l.f,[h(b)])},onabort:function(b){a.a(l.g,[h(b)])}})};a.e.create=function(b,d,c,e,f,g,h,l){var k={keyPath:a.l(c)?null:c,autoIncrement:a.K(e)?e:!1};a.c.I({c:b,d:function(b){try{b.e=b.db.createObjectStore(d,k),a.a(f,[b])}catch(c){b.error=c,a.j(c.code,a.window.Y.CONSTRAINT_ERR)&&(b.message="Store already exists"),a.a(g,
[b])}},f:function(b){a.a(g,[b])},g:function(b){a.a(h,[b])},o:function(b){a.a(l,[b])}})};a.e.b=function(b,d,c){b=a.transaction.create(b,d);b=a.b(b)?b.objectStoreNames:null;d=a.contains(b,d)?!0:!1;a.a(c,[d]);return d};a.e.options=function(b,d,c){b={keyPath:a.l(b)?null:b,autoIncrement:a.K(d)?d:!1};a.a(c,[b]);return b};a.e.show=function(b,d,c){b=a.transaction.create(b,d).objectStore(d);b=a.l(b)?null:{name:b.name,indexes:b.indexNames,key:b.keyPath};a.a(c,[b]);return b};a.G.create=function(b,d,c,e,f,g){var h=
[],l={c:b,G:d,r:c,d:e,f:f,g:g},k=!1;a.F(d,function(c,q){var m=d[q],n=null,s=!1;a.Q(m)&&(m=a.e.options(m));a.e.b(b,q)?(l.message="Store already exists",l.e=q,a.a(f,[l]),k=!0):(a.m(m,"key")?(n=m.key,s=m.$):a.i(m,function(a){n=a;s=!1}),function(a,b){h.push([a,b])}(a.e.create,[b,q,n,s,e,f,g]))});if(a.j(k,!0))return!1;a.O(h,function(){a.a(c,arguments)},function(){a.a(e,arguments)},function(){a.a(f,arguments)},function(){a.a(g,arguments)});return!0};a.G.show=function(b,d){var c=a.n[b].objectStoreNames;
a.a(d,[c]);return c};a.index.create=function(b,d,c,e,f,g,h,l,k,p,q){var m={c:b,e:d,key:c,name:e,unique:f,R:g,d:h,f:l,g:k,o:q,w:p};f=f||!1;g=g||!1;a.c.I({c:b,d:function(b){b=b.db;var k;try{k=b.transaction(d,a.transaction.X()).objectStore(d);try{k.createIndex(e,c,{unique:f,multirow:g}),a.a(h,[m])}catch(p){m.error=p,a.a(l,[m])}}catch(q){m.error=q,a.a(l,[m])}},f:function(){a.a(l,[m])},g:function(){a.a(k,[m])},o:function(){a.a(q,[m])},w:function(){a.a(p,[m])}})};a.index.show=function(b,d,c,e){b=a.transaction.create(b,
d);c=a.b(b)?b.index(c):null;c=a.l(c)?null:{name:c.name,key:c.keyPath,unique:c.unique};a.a(e,c);return c};a.index.b=function(b,d,c,e){b=a.transaction.create(b,d);b=a.b(b)?b.indexNames:null;c=a.contains(b,c)?!0:!1;a.a(e,[c]);return c};a.C.create=function(b,d,c,e,f,g,h){var l=[],k={c:b,C:d,r:c,d:e,f:f,g:g,o:h},p=!1;a.i(d,function(c,d){a.i(d,function(d,h){var m,r=!1,t=!1,v;a.index.b(b,c,d)?(k.error="Index already exists",p=!0,a.a(f,[k])):(a.m(h,"key")?(m=h.key,r=h.unique):a.i(h,function(b){v=h[b];m=b;
a.m(v,"unique")||a.m(v,"multirow")?(r=v.unique,t=v.R):r=h[b]}),function(a,b){l.push([a,b])}(a.index.create,[b,c,m,d,r,t,e,f,g]))})});if(a.j(p,!0))return!1;a.O(l,function(){a.a(c,arguments)},function(){a.a(e,arguments)},function(){a.a(f,arguments)},function(){a.a(g,arguments)},function(){a.a(h,arguments)});return!0};a.index["delete"]=function(b,d,c,e,f,g,h,l){var k={c:b,e:d,name:c,d:e,f:f,g:g,o:l,w:h};a.c.I({c:b,e:d,d:function(b){b=b.D;try{b.deleteIndex(c),a.a(e,[k])}catch(d){k.error=d,a.a(f,[k])}},
f:function(){a.a(f,[k])},g:function(){a.a(g,[k])},o:function(){a.a(l,[k])},w:function(){a.a(h,[k])}})};a.C.show=function(b,d,c){b=a.transaction.create(b,d).indexNames;a.a(c,[b]);return b};a.transaction.T=function(){return a.B.READ_ONLY};a.transaction.t=function(){return a.B.READ_WRITE};a.transaction.write=function(){return a.B.READ_WRITE};a.transaction.X=function(){return a.B.VERSION_CHANGE};a.transaction.create=function(b,d,c,e){b=a.c[b];c=c||a.transaction.t();d=b.transaction([d],c);a.a(e,[d]);return d};
a.cursor.direction.next=function(b){return b?a.window.IDBCursor.NEXT_NO_DUPLICATE:a.window.IDBCursor.NEXT};a.cursor.direction.S=function(){return a.window.IDBCursor.PREV_NO_DUPLICATE};a.cursor.L=function(b){return a.u(b)&&b>=a.cursor.direction.next()&&b<=a.cursor.direction.S()?!0:!1};a.p.only=function(b){return a.p.get(b,null,null,null,null)};a.p.left=function(b){return a.p.get(null,b,null,!1,null)};a.p.ca=function(b){return a.p.get(null,b,null,!0,null)};a.p.right=function(b){return a.p.get(null,
null,b,null,!1)};a.p.da=function(b){return a.p.get(null,null,b,null,!0)};a.p.get=function(b,d,c,e,f){var g=!1;a.b(d)&&a.b(c)&&a.b(e)&&a.b(f)?g=a.window.IDBKeyRange.bound(d,c,e,f):a.b(d)&&a.b(e)?g=a.window.IDBKeyRange.lowerBound(d,e):a.b(c)&&a.b(f)?g=a.window.IDBKeyRange.upperBound(c,f):a.b(b)&&(g=a.window.IDBKeyRange.only(b));return g};a.h.add=function(b,d,c,e,f,g){function h(a){l.event=a;return l}var l={c:b,e:d,data:c,d:e,f:f,g:g};b=a.transaction.create(b,d,a.transaction.t()).objectStore(d);c=a.k(c)?
c():a.s(c);c=b.add(c);c=a.extend(c,{onsuccess:function(b){l.result=a.h.value(b);return a.a(e,[h(b)])},onerror:function(b){return a.a(f,[h(b)])},onabort:function(b){return a.a(g,[h(b)])}})};a.h["delete"]=function(b,d,c,e,f,g,h){function l(a){k.event=a;return k}var k={c:b,e:d,key:c,d:e,f:f,g:g,r:h};b=a.transaction.create(b,d,a.transaction.write()).objectStore(d)["delete"](c);a.extend(b,{onsuccess:function(b){k.result=a.h.value(b);return a.a(e,[l(b)])},onerror:function(b){return a.a(f,[l(b)])},onabort:function(b){return a.a(g,
[l(b)])}})};a.h.get=function(b,d,c,e,f,g,h,l){function k(a){p.event=a;return p}var p={c:b,e:d,key:c,index:e,d:f,f:g,g:h,r:l};b=a.transaction.create(b,d,a.transaction.T(),l);d=b.objectStore(d);var q,m;if(a.b(e))try{q=d.index(e),m=q.get(c)}catch(n){return p.error=n,a.a(g,[p])}else m=b.get(c);a.extend(m,{onsuccess:function(b){p.value=a.h.value(b);a.a(f([k(b)]))},onerror:function(b){return a.a(f([k(b)]))},onabort:function(b){return a.a(f([k(b)]))}})};a.h.put=function(b,d,c,e,f,g,h){function l(a){k.event=
a;return k}var k={c:b,e:d,data:c,d:f,f:g,g:h};b=a.transaction.create(b,d,a.transaction.t()).objectStore(d);var p;c=a.k(c)?c():a.s(c);try{p=a.b(e)?b.put(c,e):b.put(c),p=a.extend(p,{onsuccess:function(b){k.result=a.h.value(b);return a.a(f,[l(b)])},onerror:function(b){return a.a(g,[l(b)])},onabort:function(b){return a.a(h,[l(b)])}})}catch(q){k.error=q,a.a(g,[l(k)])}};a.h.result=function(b){b=a.m(b,"event")?b.event:b;return a.m(b,"result")?b.result:null};a.h.update=function(b,d,c,e,f,g,h,l,k,p,q,m){var n=
0;m=m||null||null;a.h.get(b,d,c,e,function(c){var e=a.h.value(c.event),r=!1,t={},v;a.b(e)&&(a.k(f)?f=f(e):a.i(f,function(b,c){var d=e[b];t[b]=a.k(c)?c(d):d}),a.b(h)&&a.i(h,function(b,c){var d=e[b];a.k(c)&&(c=c(d));a.b(d)&&a.b(c)&&a.q(e[b],c)&&(r=!0)}),a.j(g,!1)&&a.b(e)?(v=a.s(e),a.i(f,function(b,c){var d=f[b],e=v[b];c=a.k(d)?d(e):d;v[b]=c}),t=v):t=f,a.j(r,!1)&&(a.l(m)||n<m)&&a.h.put(b,d,t,null,function(b){b.update=t;a.a(l,[b])},k,p,q),a.j(r,!1)&&(a.l(m)||n<m)&&(n+=1))},k,p)};a.h.value=function(b){b=
a.m(b,"event")?b.event:b;return a.m(b,"target.result")?b.target.result:null};a.cursor["delete"]=function(b,d,c,e,f,g,h,l,k,p,q){function m(a){n.event=a;return n}var n={c:b,e:d,index:c||null,M:e,direction:f||a.cursor.direction.next(),J:h||null,N:g||null,d:l,f:k,g:p,r:q};b=a.transaction.create(b,d,a.transaction.t());var s,u,r=0;try{a.l(c)?s=b.openCursor(e,f):(u=b.index(c),s=u.openCursor(e,f)),s=a.extend(s,{onsuccess:function(b){var c=a.h.value(b),d=a.cursor.value(b),e=!1,f;n=m(b);n.result=d;a.b(h)&&
a.i(h,function(b,c){var f=a.m(d,b)?d[b]:null;a.k(c)&&(c=c(f));a.b(f)&&a.b(c)&&a.q(f,c)&&(e=!0)});if(a.j(e,!1)&&a.b(c)&&a.b(d))try{f=c["delete"](),f=a.extend(f,{onsuccess:function(){r+=1;if(a.u(g)&&r>=g)a.a(q,[n]);else if(a.b(c)&&a.k(c["continue"]))try{c["continue"]()}catch(b){a.a(q,[n])}a.a(l,arguments)},onerror:function(){a.a(k,arguments)}})}catch(p){return n.error=p,a.a(k,[n])}else return a.a(k,[n])},onerror:function(b){return a.a(k,[m(b)])},onabort:function(b){return a.a(p,[m(b)])}})}catch(t){n.error=
t,a.a(k,[n])}};a.cursor.get=function(b,d,c,e,f,g,h,l,k,p,q){function m(a){n.event=a;return n}var n={c:b,e:d,index:c||null,M:e,direction:a.cursor.L(f)?f:a.cursor.direction.next(),J:g||null,N:h||null,d:l,f:k,g:p,r:q};b=a.transaction.create(b,d,a.transaction.t());var s,u,r=0;try{a.l(c)?s=b.openCursor(e,f):(u=b.index(c),s=u.openCursor(e,f)),s=a.extend(s,{onsuccess:function(b){var c=a.h.value(b),d=a.cursor.value(b),e=!1;n=m(b);n.result=d;a.b(g)&&a.i(g,function(b,c){var f=a.m(d,b)?d[b]:null;a.k(c)&&(c=
c(f));a.b(f)&&a.b(c)&&a.q(f,c)&&(e=!0)});x.j(e,!0)?a.a(k,[n]):a.a(l,[n]);r+=1;if(a.u(h)&&r>=h)a.a(q,[n]);else if(a.b(c)&&a.k(c["continue"]))try{c["continue"]()}catch(f){a.a(q,[n])}},onerror:function(b){return a.a(k,[m(b)])},onabort:function(b){return a.a(p,[m(b)])}})}catch(t){n.error=t,a.a(k,[n])}};a.cursor.result=function(b){return a.h.value(b)};a.cursor.update=function(b,d,c,e,f,g,h,l,k,p,q,m,n){function s(a){u.event=a;return u}var u={c:b,e:d,index:c||null,M:e,direction:a.cursor.L(g)?g:a.cursor.direction.next(),
J:k||null,replace:l||!0,N:h||null,d:p,f:q,g:m,r:n},r=a.transaction.create(b,d,a.transaction.t()),t=0;a.l(c)?e=r.openCursor(e,g):(c=r.index(c),e=c.openCursor(e,g));a.extend(e,{onsuccess:function(c){function e(){t+=1;if(a.u(h)&&t>=h)a.a(n,[s(c)]);else{var b=g.update(w);u.update=w;b=a.extend(b,{onsuccess:function(b){u.update=w;a.a(p,[s(b)]);g["continue"]()},f:function(b){return a.a(q,[s(b)])}})}}var g=a.h.value(c),r=a.s(a.cursor.value(c)),z=!1,w={},y;u.result=r;u.cursor=g;u=s(c);a.b(r)?(a.k(f)?w=f(r):
(a.i(f,function(b,c){var d=r[b];w[b]=a.k(c)?c(d):d}),a.b(k)&&a.i(k,function(b,c){var d=r[b];a.k(c)&&(c=c(d));a.b(d)&&a.b(c)&&a.q(r[b],c)&&(z=!0)}),a.j(l,!1)&&a.b(r)?(y=a.s(r),a.i(f,function(b,c){var d=f[b],e=y[b];c=a.k(d)?d(e):d;y[b]=c}),w=y):w=f,a.j(z,!1)&&(a.l(h)||t<h)&&a.h.put(b,d,w,null,function(b){b.update=w;a.a(p,[b])},q,m,n)),e()):a.a(q,[r])},onerror:function(b){return a.a(q,[s(b)])},onabort:function(b){return a.a(m,[s(b)])}})};a.cursor.value=function(b){b=a.m(b,"event")?b.event:b;return a.m(b,
"target.result.value")?b.target.result:null};return a}();
